#!/bin/bash
for attempt in {99..99}
do
   for brain in {1..484}
   do
      python ./ozstar_train.py --res 219 --subj $brain --epoch 30000 --sample 100 --fns 'streamlines' 'node_str' 'target_node' 'target_region' 'hub' 'neighbour_just_visited_node' 'edge_con_diff_region' 'inter_regional_connections' 'prev_visited_region' 'target_func_region' 'edge_con_diff_func_region' 'prev_visited_func_region' --save R01_sl_ns_${brain}_${attempt}.pt --batch 1 --savefreq 1000 &#> log01.txt &
      python ./ozstar_train.py --res 219 --subj $brain --epoch 30000 --sample 100 --fns 'node_str' 'target_node' 'target_region' 'hub' 'neighbour_just_visited_node' 'edge_con_diff_region' 'inter_regional_connections' 'prev_visited_region' 'target_func_region' 'edge_con_diff_func_region' 'prev_visited_func_region' --save R02_sl_ns_${brain}_${attempt}.pt --batch 1 --savefreq 1000 &#> log02.txt &
      python ./ozstar_train.py --res 219 --subj $brain --epoch 30000 --sample 100 --fns 'streamlines' 'target_node' 'target_region' 'hub' 'neighbour_just_visited_node' 'edge_con_diff_region' 'inter_regional_connections' 'prev_visited_region' 'target_func_region' 'edge_con_diff_func_region' 'prev_visited_func_region' --save R03_sl_ns_${brain}_${attempt}.pt --batch 1 --savefreq 1000 & #> log03.txt & # excl. node_str
      python ./ozstar_train.py --res 219 --subj $brain --epoch 30000 --sample 100 --fns 'streamlines' 'node_str' 'target_region' 'hub' 'neighbour_just_visited_node' 'edge_con_diff_region' 'inter_regional_connections' 'prev_visited_region' 'target_func_region' 'edge_con_diff_func_region' 'prev_visited_func_region' --save R04_sl_ns_${brain}_${attempt}.pt --batch 1 --savefreq 1000 #> log04.txt # excl. target_node
      python ./ozstar_train.py --res 219 --subj $brain --epoch 30000 --sample 100 --fns 'streamlines' 'node_str' 'target_node' 'hub' 'neighbour_just_visited_node' 'edge_con_diff_region' 'inter_regional_connections' 'prev_visited_region' 'target_func_region' 'edge_con_diff_func_region' 'prev_visited_func_region' --save R05_sl_ns_${brain}_${attempt}.pt --batch 1 --savefreq 1000 &#> log05.txt &
      python ./ozstar_train.py --res 219 --subj $brain --epoch 30000 --sample 100 --fns 'streamlines' 'node_str' 'target_node' 'target_region' 'neighbour_just_visited_node' 'edge_con_diff_region' 'inter_regional_connections' 'prev_visited_region' 'target_func_region' 'edge_con_diff_func_region' 'prev_visited_func_region' --save R06_sl_ns_${brain}_${attempt}.pt --batch 1 --savefreq 1000 &#> log06.txt & # excl. hub
      python ./ozstar_train.py --res 219 --subj $brain --epoch 30000 --sample 100 --fns 'streamlines' 'node_str' 'target_node' 'target_region' 'hub' 'neighbour_just_visited_node' 'edge_con_diff_region' 'prev_visited_region' 'target_func_region' 'edge_con_diff_func_region' 'prev_visited_func_region' --save R07_sl_ns_${brain}_${attempt}.pt --batch 1 --savefreq 1000 & #> log07.txt &
      python ./ozstar_train.py --res 219 --subj $brain --epoch 30000 --sample 100 --fns 'streamlines' 'node_str' 'target_node' 'target_region' 'hub' 'neighbour_just_visited_node' 'inter_regional_connections' 'prev_visited_region' 'target_func_region' 'edge_con_diff_func_region' 'prev_visited_func_region' --save R08_sl_ns_${brain}_${attempt}.pt --batch 1 --savefreq 1000 #> log08.txt &
      python ./ozstar_train.py --res 219 --subj $brain --epoch 30000 --sample 100 --fns 'streamlines' 'node_str' 'target_node' 'target_region' 'hub' 'neighbour_just_visited_node' 'edge_con_diff_region' 'prev_visited_region'	'target_func_region' 'edge_con_diff_func_region' 'prev_visited_func_region' --save R09_sl_ns_${brain}_${attempt}.pt --batch 1 --savefreq 1000 & #> log09.txt 	
      python ./ozstar_train.py --res 219 --subj $brain --epoch 30000 --sample 100 --fns 'streamlines' 'node_str' 'target_node' 'target_region' 'hub' 'neighbour_just_visited_node' 'edge_con_diff_region' 'inter_regional_connections' 'target_func_region' 'edge_con_diff_func_region' 'prev_visited_func_region' --save R10_sl_ns_${brain}_${attempt}.pt --batch 1 --savefreq 1000 & #> log10.txt &
      python ./ozstar_train.py --res 219 --subj $brain --epoch 30000 --sample 100 --fns 'streamlines' 'node_str' 'target_node' 'target_region' 'hub' 'neighbour_just_visited_node' 'edge_con_diff_region' 'inter_regional_connections' 'prev_visited_region' 'edge_con_diff_func_region' 'prev_visited_func_region' --save R11_sl_ns_${brain}_${attempt}.pt --batch 1 --savefreq 1000 & #> log11.txt &
      python ./ozstar_train.py --res 219 --subj $brain --epoch 30000 --sample 100 --fns 'streamlines' 'node_str' 'target_node' 'target_region' 'hub' 'neighbour_just_visited_node' 'edge_con_diff_region' 'inter_regional_connections' 'prev_visited_region' 'target_func_region' 'prev_visited_func_region' --save R12_sl_ns_${brain}_${attempt}.pt --batch 1 --savefreq 1000 & #> log12.txt &
      python ./ozstar_train.py --res 219 --subj $brain --epoch 30000 --sample 100 --fns 'streamlines' 'node_str' 'target_node' 'target_region' 'hub' 'neighbour_just_visited_node' 'edge_con_diff_region' 'inter_regional_connections' 'prev_visited_region' 'target_func_region' 'edge_con_diff_func_region' --save R13_sl_ns_${brain}_${attempt}.pt --batch 1 --savefreq 1000 #> log13.txt
   done
done
